_BASE_: "../../../../configs/Base-RCNN-DilatedC5.yaml"
MODEL:
  META_ARCHITECTURE: "SemanticSegmentor"
  BACKBONE:
    FREEZE_AT: 0
  SEM_SEG_HEAD:
    NAME: "DeepLabV3Head"
    IN_FEATURES: ["res5"]
    ASPP_CHANNELS: 256
    ASPP_DILATIONS: [6, 12, 18]
    ASPP_DROPOUT: 0.1
    CONVS_DIM: 256
    COMMON_STRIDE: 16
    NUM_CLASSES: 2
    LOSS_TYPE: "hard_pixel_mining"
DATASETS:
  TRAIN: ("custom_dataset_train",)
  TEST: ("custom_dataset_test",)
SOLVER:
  BASE_LR: 0.01
  MAX_ITER: 10000
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  IMS_PER_BATCH: 7
# INPUT:
#   MIN_SIZE_TRAIN: (512,)
#   MIN_SIZE_TRAIN_SAMPLING: "choice"
#   MIN_SIZE_TEST: 512
#   MAX_SIZE_TRAIN: 512
#   MAX_SIZE_TEST: 512
#   CROP:
#     ENABLED: True
#     TYPE: "absolute"
#     SIZE: (512, 512)
#     SINGLE_CATEGORY_MAX_AREA: 1.0
INPUT:
  MIN_SIZE_TRAIN: (1080,)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1080
  MAX_SIZE_TRAIN: 1920
  MAX_SIZE_TEST: 1920
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (360, 640)
    SINGLE_CATEGORY_MAX_AREA: 1.0
DATALOADER:
  NUM_WORKERS: 10
